### PR TITLE
Fix #2410, #2411, #2151: DateTimeOffset

### LINKED ISSUE #2151: DateTimeOffset: import not found: toOffset
Code:

```f#
module Test


open Fable.Core.JS
open System

let now = DateTimeOffset.Now
let now2 = now.ToOffset(TimeSpan.Zero)

console.log(now, now2)
```

Error:

```
Uncaught SyntaxError: import not found: toOffset
```

[REPL Link](https://fable.io/repl/#?code=LYewJgrgNgpgBAFRgZwC4ChMgA4wHZwBiAhgEawB0AwiAE4wUBSAyujvnMwJ5ozCaxUcPCADucALxwAIsVQwEAS2AwA8gDN1yGKgoA5MekHCxAJkknRFBCA1adACiUrm2YngoAtGLRABKTABjEDxkEEooEABzBxFRABpLUwCgA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

### LINKED ISSUE #2410: DateTimeOffset: Invalid offsets are accepted or raise incorrect error
### Description
DateTimeOffset allows for Offsets up to `+/- 14h`. But in Fable offsets between `14h` & `15h` and offsets `< -14h` are accepted. Offsets `< -24h` raise exception -- but with wrong message.

### Repro code & results

**between `14h` & `15h`**
```fsharp
printfn "%A" <| DateTimeOffset(2020, 02, 20, 20, 20, 20, TimeSpan.FromHours(14.1))
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQWQCcCWESAZtAEQCkAgmVADwA+UAIgIYoAq+qYA8scQRgkACgBMABkkAaKFNkyoi5RNlceMEKwgA6AGK5gqABLAArrgQiAjABYd1gJSOgA&html=Q&css=Q))

.NET:
> Exception: `Offset must be within plus or minus 14 hours. (Parameter 'offset')`  

Fable:
> 2020-02-20 20:20:20 +14:06 

**between `-14h` & `-24h`**
```fsharp
printfn "%A" <| DateTimeOffset(2020, 02, 20, 20, 20, 20, TimeSpan.FromHours(-14.1))
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQWQCcCWESAZtAEQCkAgmVADwA+UAIgIYoAq+qYA8scQRgkACgBMABkkAaKFNkyoi5RNlceMEKwgA6AGK5gqABLAArrgQiAtAEYALDtsBKZ0A&html=Q&css=Q))

.NET:
> Exception: `Offset must be within plus or minus 14 hours. (Parameter 'offset')`  

Fable:
> 2020-02-20 20:20:20 -14:06 

**`< -24h`**
```fsharp
printfn "%A" <| DateTimeOffset(2020, 02, 20, 20, 20, 20, TimeSpan.FromHours(-100))
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQWQCcCWESAZtAEQCkAgmVADwA+UAIgIYoAq+qYA8scQRgkACgBMABkkAaKFNkyoi5RNlceMEKwgA6AGK5gqABLAArrgQiAtAEYJEnRICUzoA&html=Q&css=Q))

.NET:
> Exception: `Offset must be within plus or minus 14 hours. (Parameter 'offset')`  

Fable:
> Exception: `The parameters describe an unrepresentable Date` 

more examples: [repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQWA2YlQrJQAUwAZuQvgFxQAqAlqmDCAIYQA0pYAHuADGKACYBRAE4TgEusgmMIAcyigkjYBACUWqAF4sUI1BAKISctABERdctWVqBPVACkCK6QpV8AOnrAMEhmSiQ6hsYRRngEEmAI+lBRxkbBcMkpKQAi7ChMLADyjvgkAEwADACMACw8AJw8lZWNAGw8pQDsPOU83k5aGZlGAD4AfFAFANaDRgDujEgAFjNQw1D8UAC0oyspktIS63xYyai5gotQcQg8-EKi+zJQ80vJa1NQIkjAPABymmAtuNTIoLNYjIAUckA8H90O5gYRgERQHJ5ZhgIo+JA8WbsBKuACCni+wDeE0mn2+PBgwBYUCsnm2JjMYLpRkAMuSwgTw0RQR4SHgAIwArgQcXjCRSSZgUu9ycSqTTAWApECmaDLKyoByjvdEbypE9BJokOxFIoVAADdwWwUi564twS5WHYmkvlHBW0+mqkHmDWeKDQzm6pF87EO91WhAWzz8XwAWXiCHYSjAboNh34nqVKtmi0gRwTSZTYF8AGFjaaIAlnUCVr6WQGgzruXrI9bwwl29HYyq44mEMnU+mDh7YIr1rn89AIMACAAeNb94up8uVxQ1lXbevM-3s4Ot0MZqBRm1QYWiiPH0+9zN8IuDkukgD6qvIppwL0uVgAkhAAG7sDgjBIoIuJgFYJyYDELbCP8SB-ggIFgAASpwqaJNSXoYk4UCoEKxACoCX6KCYOAEaohyoIoFE1FAizAEKEiQdg0H4CYwBIeo-6Ai4ADayT5KwHAQL4ABi0ioAAEoxEgICQlTlOUvjlFotxcnBc6IchaHKGm0rGEJbCcOJkkyUx8mlNUKlqbBSDwdpIioeh+kpEZIkKQArI03S2XCmkIdWOkuYJaLGaJEk0uZcleTZ6n3A5QVObpw4GUY7mcAptRQJ5DRQKp8XcolSHJSFaUMGFImmVFsnyTUvh1H5Gn2VpSXOXpoUsOF1XSbVWW+JUTUJa1JXtalbmVZlNQ+flQ1FSNwUdeVGURWZfX1QVUD-BA+kALq4OxO1KLkjA8YkAnLZNq01RZJCbBttnba5hlXXd01bM0s2FQFjljc96Wvfd2WbLlvnfS1gWjSl-0VV1VWRb1t33Z5cV2cVi3jS9cOZcjPD3WDaMLaVS0Tdj12IzFmylAAzKj-kQ790OdcJOM03joNfYTkMYzDK09dF8lU9Zm30+jxOYwDZN3VZeNVATotE39zPdQjAtvUpdPNWLSuYPtrEgJxCynYCAACUBHSdPFYGMUAADKMMgvgLMqhDxEgWBAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

### Related information

* Versions:
  * Fable: `3.1.5`
  * Repl: `3.1.5`

Note: I'm currently working on a fix.

### LINKED ISSUE #2411: `DateTimeOffset(DateTime, offset)` fails when `DateTime.Kind = Unspecified` and `offset` doesn't match local timezone
### Description

`DateTimeOffset(DateTime(Kind = Unspecified), offset)` fails for offsets not matching local timezone.

<br/>

`DateTimeOffset(DateTime, offset: TimeSpan)` creates a DateTimeOffset from passed Date with custom offset -- as long as that offset follows the specified `DateTime.Kind`:
* `UTC`: only `offset = 0` valid
* `Local`: offset must match local time zone: `DateTimeOffset(DateTime.Now, TimeSpan.FromHours(1.0))` (Standard Time in Central Europe)

Last `Kind` is `Unspecified`:
* No offset specified (`DateTimeOffset(DateTime)`): uses local offset
* with offset: uses specified offset. But in Fable it still behaves like `Local` and allows only offsets matching the local timezone.

### Repro code & Output

```fsharp
let unspecified = DateTime(2008, 5, 1, 8, 30, 52, DateTimeKind.Unspecified)

let offset = TimeSpan.FromHours(1.6)  // using timezone offset that's (hopefully...) not used anywhere
printfn "%A" <| DateTimeOffset(unspecified, offset)
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYCh0BsxKgVwgXAGMBLAMzLABMoBeKAEQEMUAVM1MACgCYADAIAcAGigBWcQEZxYqAGYB4iX3GsOXMAGkyEGgDoAqkVKVqNAJSYceYBQoJcDKJ24wQLCAYBiAJ2BUAAlgfD8EHmkDADZrED89JApoACIAUgBBFKgAHgAfZjYwNzAAeQcnJB5CYjByKlpxe0dcSyA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA))

.NET:
> 2008-05-01 08:30:52 +01:36

Fable:
> Exception: `The UTC Offset of the local dateTime parameter does not match the offset argument.`

And: `DateTimeKind.Unspecified` is used when no `DateTimeKind` is explicitly given. -> This fails too:
```fsharp
let dt  = DateTime(2008, 5, 1, 8, 30, 52)

let offset = TimeSpan.FromHours(1.6)
printfn "%A" <| DateTimeOffset(dt, offset)
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYCh0BsxKgEzwF4oARAQxQBUBLVMACgCYAGFgDgBooBWbgRm5coAZhbceTAJSYceYADMFCXFBK16MEOQgA6AGIAnYKgASwAK6GEDfroBsMkIZoQkC6ACIApAEFPUAA8AD5klGAaYADySipIDITcisq4UkA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA))

.NET:
> 2008-05-01 08:30:52 +01:36

Fable:
> Exception: `The UTC Offset of the local dateTime parameter does not match the offset argument.`

Only accepted offset is `offset = local offset`:
```fsharp
let dt = DateTime(2008, 5, 1, 8, 30, 52)

let offset: TimeSpan = !! (dt?getTimezoneOffset() * -60_000)
printfn "%A" <| DateTimeOffset(dt, offset)
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYChSSgMQIYBGANmAHQDCwATmQFIICSEKVo66JSUAJlwLxQAInhQAVAJaowACgBMABnkAOADRQArGoCMa1VADM8tetkBKdpyjAAZtYRgkALigSpMEHmgD0AYnHXcAEEAIQAZAFEAfXIAeQBZAAUGCIAldCgMqABCLKhpXgB+AHMHVzAAL2AIMBjbeyRpUygAKigAWgA2eUjFeXMfMCJ7dMyygC0qsCZrYFJQ4ABjPCJSAHEHAFUkBdq7B3ykfshuf3YQKnFma2gAIgBSQJuoAB4AHyERMDLd+oO1Gz2hyAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA))

.NET:
> 2008-05-01 08:30:52 +02:00

Fable:
> 2008-05-01 08:30:52 +02:00

### Related information

* Versions:
  * Fable: `3.1.5`
  * Repl: `3.1.5`

Note: I'm currently working on this one. It's a case of: easy to fix, hard to unit test...:  
Is there a way to use a specific timezone in a unit test?  
I'm currently getting the local time zone (like above) and using that for tests. But that means: 
* different tests on different systems 
* Cannot test for both normal time and summer time (daylight saving time)
* I have to adjust unit tests to ensure they match or don't match the local offset 
* Less useful tests on systems with local time = UTC

### PR DESCRIPTION
**Pull request by Booksbaum**
* Fix #2410: Invalid offsets are accepted  
* Fix #2411: DateTime(Unspecified) fails when offset not local timezone
* Fix #2151: Implement `DateTimeOffset.toOffset`

Some test have to deal with local offset -- which is system timezone dependent.  
-> Some Tests are different on different systems.  
... but should work....hopefully.....😅

(for fixing timezone: see #2375 ... not done here)

----------------------

Additional:  
Prettier unit test error messages for exception tests:  
For test functions (in `Util/Util.fs`) like `throwsError` or `throwsAnyError`:

Previously error when an exception was expected, but not thrown, looked like:
> Error: Expected: true - Actual: false

Updated error messages (no exception):
> Error: Expected: Error "my error message" - Actual: Ok

or (wrong exception):
> Error: Expected: Error "my error message" - Actual: Error "some other message"

### CODE REVIEW

File: tests/Main/Util/Util.fs [hunk 1]
```diff
@@ -46,26 +46,89 @@ let ``1foo`` = 5
 
 open Testing
 
+module private RunResult =
+#if FABLE_COMPILER
+    let private isString value : bool =
+        Fable.Core.JsInterop.emitJsExpr
+            (value)
+            // literal string: `"foo"`   // string object: `new String("foo")`
+            "typeof $0 === \"string\" || $0 instanceof String"
```
Comment (Booksbaum) [inline tests/Main/Util/Util.fs:55]: Is there a Fable way to test for string?

It's just pretty printing in unit tests...but still...

**Comment by Booksbaum** [comment]
And there we have "should work"....

generated names for tests & running on different timezones.......lots of fun...

CI runs on offset=0.
Test `DateTime(Local),TimeSpan.FromHours(0))` was adjusted to `-1min`.
But there's already a test with `-1min` (`TimeSpan.FromSeconds(-60)`)  
-> same name


-> I need to adjust name generation (or skip test when offset = local offset). Tomorrow.

File: tests/Main/Util/Util.fs (hunk 1 above)
Comment (alfonsogarciacaro) [reply tests/Main/Util/Util.fs:55]: You can do type testing against string (as in `x :? string`) and this will be translated to `typeof x === "string"`. Currently is not checking `x instanceof String` though, maybe we should do that 🤔

**Review by alfonsogarciacaro — APPROVED** [review]

**Comment by alfonsogarciacaro** [comment]
Thanks a lot @Booksbaum! Yeah, it'd be great if we can make the PR green before merging. Let me know if I can help with something.

File: tests/Main/Util/Util.fs (hunk 1 above)
Comment (Booksbaum) [reply tests/Main/Util/Util.fs:55]: Haven't though of type pattern matching. Good idea, thanks!

(But: doesn't work in function with generic parameter:
```
error FSHARP: This runtime coercion or type test from type
    'c
to
    string
involves an indeterminate type based on information prior to this program point. Runtime type tests are not allowed on some types. Further type annotations are needed. (code 8)
```

-> parameter must be of type `obj`. Here that's ok.
)


I don't think `instanceof String` matters in practice: `String` (with capital `S`) is basically never used.... And here it's definitely not required (even if: What would happen is: String wouldn't get wrapped in quotation marks...)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot @Booksbaum!
