### PR TITLE
Fix #3306 and disable tailcalltests only for standalone

### LINKED ISSUE #3306: Fable 4: Object.assign generates invalid javascript
### Description

`Object.assign(target,source)` where `source` is an object generates invalid javascript code

### Repro code

    open Fable.Core

    let a = JS.Constructors.Object.assign({| a = 1 |}, {| b = 2 |})

or in [fable repl](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChcoAuUcUAvFAFIDKGwEAzoVgK4DGh2DqA8ggFZgOqOAwYBLAOYQAFAG8APiXJQAjFAUBfADRRFUBCoBMGzQEpcQA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q)

### Expected and actual results

Expected the generated javascript to be

    export const a = Object.assign({
        a: 1,
    }, {
        b: 2,
    });

but is was

    export const a = Object.assign({
        a: 1,
    }, ...{
        b: 2,
    });

This is invalid code and causes the exception

    TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function

### Related information

* Fable version: `4.0.0-theta-018`

This is a regression from fable 3

A work-around for fable 4 is to use

    let a = JS.Constructors.Object.assign({| a = 1 |}, [| {| b = 2 |} |]) // Note the wrapping in an array

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**

### CODE REVIEW

File: tests/Js/Main/TailCallTests.fs [hunk 1]
```diff
@@ -132,12 +132,14 @@ let tests =
...
     // TODO: temporary diabled until Fable-FCS issue is solved, see #3311
-
-    // testCase "Tailcall works with bindings" <| fun () ->
-    //     Issue3301.binding 100000 1 |> equal 100001
-
-    // testCase "Tailcall works with tuple deconstruction" <| fun () ->
-    //     Issue3301.tupleDeconstruction 100000 1 |> equal 100001
+#if !FABLE_STANDALONE
+    testCase "Tailcall works with bindings" <| fun () ->
+        printfn "Tailcall works with bindings"
```
Comment (ncave) [inline tests/Js/Main/TailCallTests.fs:137]: Perhaps this print was temporary and can be removed.
