### PR TITLE
Accessing an array out of bounds, should generates an exception like on .NET

### LINKED ISSUE #3729: IndexOutOfRangeException for bad index?
I am expecting an `IndexOutOfRangeException` here, but it just returns `undefined`
```fsharp
let xs: string[] = [||]

printfn $"{xs[0]}"
```
See [REPL](https://fable.io/repl/#?code=DYUwLgBAHgzgXBGYBOBLAdgcwNoF0IC8E2APibgFAUAOa6YAZuhACQBEA3rNgAy4C+bIA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q)
I know this is the default JS behavior. Should Fable stick to .NET semantics? 
Or could it offer a debug mode where indices are checked?

### PR DESCRIPTION
**Pull request by MangelMaxime**
Fix #3729

@ncave Could you please have a look at what I did? 

By some trial and error, I found that these places are where we handle array index access + `Array.item` which have the same behaviour.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Oups I didn't test TypeScript locally, I will have a look at it.

**Review by ncave — CHANGES_REQUESTED** [review]

File: src/fable-library/Array.fs [hunk 1]
```diff
@@ -877,13 +877,23 @@ let tail (array: 'T[]) =
...
 
-let item index (array: _[]) = array.[index]
+let item (index: int) (array: 'T[]) : 'T =
+    if index < 0 || index >= array.Length then
+        invalidArg "index" "Index was outside the bounds of the array."
+    else
+        // We need to emit JavaScript directly here
+        // otherwise we will call `item` function recursively
+        // and it will cause a stack overflow
+        emitJsExpr (index, array) "$1[$0]"
```
Comment (ncave) [inline src/fable-library/Array.fs:887]: @MangelMaxime Perhaps move this to `Native.fs`.

**Review by ncave — CHANGES_REQUESTED** [review]

File: src/fable-library/Array.fs (hunk 1 above)
Comment (MangelMaxime) [reply src/fable-library/Array.fs:887]: I didn't know about this file.

I will look to add an helper in that module

File: src/Fable.Transforms/Replacements.fs [hunk 2]
```diff
@@ -2582,8 +2582,34 @@ let arrayModule (com: ICompiler) (ctx: Context) r (t: Type) (i: CallInfo) (_: Ex
         Helper.LibCall(com, "List", "ofArray", t, args, i.SignatureArgTypes, genArgs = i.GenericArgs, ?loc = r)
         |> Some
     | ("Length" | "Count"), [ arg ] -> getFieldWith r t arg "length" |> Some
-    | "Item", [ idx; ar ] -> getExpr r t ar idx |> Some
-    | "Get", [ ar; idx ] -> getExpr r t ar idx |> Some
+    | "Item", [ idx; ar ] ->
+        Helper.LibCall(
+            com,
+            "Array",
+            "item",
```
[the remark this answers is not in the document]
Comment (MangelMaxime) [reply src/Fable.Transforms/Replacements.fs:2589]: I thought about it but didn't pursue in that direction for some reason.

I will make the changes

**Comment by MangelMaxime** [comment]
Failing test is this one:

https://github.com/fable-compiler/Fable/blob/53238bc4278d33de8b2548af747aa18fef234474/tests/Js/Main/MiscTests.fs#L491-L499

Failing on this line `equal<float64>(80, item(1, ((parsed["widget"])["text"])["size"])["height"]);` because TypeScript infers the type of `item<'T>` to `item<unknown>`.

Should we provide the generic type to `item` ? Also looking at the compilers directives for that test they feels strange. Is it expected that this test is only for TypeScript or should it run for JavaScript too ?

@ncave

**Comment by ncave** [comment]
@MangelMaxime Also, on an unrelated note, recently we tend to merge a lot of commits with every PR.
Perhaps we should always "squash and merge" the PRs instead, otherwise the commit history becomes somewhat unusable to figure out what changed and when.

**Comment by MangelMaxime** [comment]
> Can you paste the TS code that was generated for the test?

Generated code looks like this:

```ts
testCase("Fable.JsonProvider works", (): void => {
    const parsed: any = JSON.parse(ANOTHER_JSON);
    equal<boolean>(false, (parsed["widget"])["debug"]);
    equal<string>("lots of", ((parsed["widget"])["text"])["data"]);
    equal<float64>(80, item(1, ((parsed["widget"])["text"])["size"])["height"]);
    equal<float64>(500, ((parsed["widget"])["text"])["vOffset"]);
})
```

> @MangelMaxime Also, on an unrelated note, recently we tend to merge a lot of commits with every PR.
> It may be a good idea to always "squash and merge" the PRs instead, otherwise the commit history becomes somewhat unusable to figure out what changed and when.

Noted, I agree and it will avoid commits like `Update changelog`... I will give it a try and we will see how it looks like.

**Comment by MangelMaxime** [comment]
I didn't think about it.

I will also have a look at the setter code.

**Comment by MangelMaxime** [comment]
I manage to add the fix for `Array.set` and `ar[idx] <- value` syntax.

For the second one, I add to unwrap `fableExpr` in `transformSet` quite a bit but I didn't see any other places to capture the `ExprSet`. And it seems like some other module do make some call to `libCall` even if this is not the norm in that file.

**Review by ncave — APPROVED** [review]

File: tests/Js/Main/MiscTests.fs [hunk 3]
```diff
@@ -489,7 +489,12 @@ let tests =
         to_str () |> equal $"{()}"
 
 #if FABLE_COMPILER
-#if !FABLE_COMPILER_JAVASCRIPT
+#if !FABLE_COMPILER_TYPESCRIPT
+    // The tests seems to cause problems in TypeScript because of the typing
+    // system. We suppose this is probably due to the TypeProvider generation
+    // so for now we just ignore that situation hoping this is not
+    // indicative of other potential issues like this
+    // See: https://github.com/fable-compiler/Fable/pull/3748
```
Comment (ncave) [inline tests/Js/Main/MiscTests.fs:497]: @MangelMaxime Looks like that test is failing for JS too

Comment (MangelMaxime) [reply tests/Js/Main/MiscTests.fs:497]: This seems to be because I forgot to update the compiler directive for the `open` statement.

I have it working locally now, let's hope this is the final CI run and we can merge this PR.

Comment (MangelMaxime) [reply tests/Js/Main/MiscTests.fs:497]: Looks like not, the test was disable for JavaScript because when testing using `fable-standalone` we don't support TypeProviders. 

But ok, that's not related to my PR changes will fix it with an additional compiler directive.

File: tests/Js/Main/MiscTests.fs [hunk 4]
```diff
@@ -468,7 +468,7 @@ type Order =
         quantity : int<kg>
     }
 
-#if !FABLE_COMPILER_TYPESCRIPT
+#if FABLE_COMPILER && !FABLE_COMPILER_TYPESCRIPT && !NPM_PACKAGE_FABLE_COMPILER_JAVASCRIPT
```
Comment (ncave) [inline tests/Js/Main/MiscTests.fs:471]: @MangelMaxime I wonder if we can simplify this to be just:
```fs
#if !FABLE_COMPILER
```
instead of introducing yet another define:
```fs
#if FABLE_COMPILER && !FABLE_COMPILER_TYPESCRIPT && !NPM_PACKAGE_FABLE_COMPILER_JAVASCRIPT
```
