### PR TITLE
[Python] Reenable type aliasing for imports with name "*" #4089

### LINKED ISSUE #4089: Python Fable-alpha.10 does not alias imports introducing "Reassignment" errors
Using `Thoth.Json.Python` in Fable 5.0.0-alpha.9 we get in `thoth_json_python/encode.py` the following:

```py
import json as json_1
...

def Decode_fromString(decoder: Decoder_1[Any], value: str) -> FSharpResult_2[Any, str]:
    try: 
        json: Any = json_1.loads(value) # This is the relevant line
        match_value: FSharpResult_2[_T, tuple[str, ErrorReason_1[Any]]] = decoder.Decode(Decode_helpers, json)
        if match_value.tag == 1:
            final_error: tuple[str, ErrorReason_1[Any]]
            tupled_arg: tuple[str, ErrorReason_1[Any]] = match_value.fields[0]
            final_error = Helpers_prependPath("$", tupled_arg[0], tupled_arg[1])
            return FSharpResult_2(1, error_to_string(Decode_helpers, final_error[0], final_error[1]))

        else: 
            return FSharpResult_2(0, match_value.fields[0])

```

Due to `json: Any = json_1.loads(value)` we must alias `import json` or we get:

```bash
Traceback (most recent call last):
  File "C:\Users\Kevin\source\repos\Fable\src\quicktest-py\quicktest.py", line 83, in <module>
    main(sys.argv[1:])
  File "C:\Users\Kevin\source\repos\Fable\src\quicktest-py\quicktest.py", line 73, in main
    result: FSharpResult_2[dict[str, Any], str] = Decode_fromString(decoder, content)
  File "C:\Users\Kevin\source\repos\Fable\src\quicktest-py\fable_modules\thoth_json_python\decode.py", line 99, in Decode_fromString
    raise match_value_1
  File "C:\Users\Kevin\source\repos\Fable\src\quicktest-py\fable_modules\thoth_json_python\decode.py", line 79, in Decode_fromString
    json: Any = json.loads(value)
UnboundLocalError: local variable 'json' referenced before assignment
```

If we go one version higher `fable-5.0.0-alpha.10` we only get `import json` without alias.

### PR DESCRIPTION
**Pull request by Freymaurer**
Closes #4089 

@MangelMaxime

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@Freymaurer Is this PR ready for review ?

**Comment by Freymaurer** [comment]
Yes! Please have a look!

File: src/Fable.Transforms/Python/Fable2Python.fs [hunk 1]
```diff
@@ -4291,7 +4291,8 @@ module Util =
         // printfn "getIdentForImport: %A" (moduleName, name)
         match name with
         | None -> Path.GetFileNameWithoutExtension(moduleName)
-        | Some name -> name |> Naming.toSnakeCase |> getUniqueNameInRootScope ctx
+        | Some name -> name |> Naming.toSnakeCase
```
Comment (dbrattli) [inline src/Fable.Transforms/Python/Fable2Python.fs:4294]: This looks like just a formatting change. How can this fix anything?

Comment (MangelMaxime) [reply src/Fable.Transforms/Python/Fable2Python.fs:4294]: It seems like now `getUniqueNameInRootScope ctx` is applied to both branches and not just `| Some name`

What I mean, is that it is now applied to `Path.GetFileNameWithoutExtension(moduleName)` too

Comment (dbrattli) [reply src/Fable.Transforms/Python/Fable2Python.fs:4294]: Aha, now I get it 🙈 Thanks

Comment (Freymaurer) [reply src/Fable.Transforms/Python/Fable2Python.fs:4294]: Correct!

File: tests/Python/TestPyInterop.fs [hunk 2]
```diff
@@ -164,14 +164,6 @@ let factorial (count : int) : int =
 let ``test emitPyStatement works with parameters`` () =
     factorial 5 |> equal 120
 
-[<Fact>]
```
Comment (dbrattli) [inline tests/Python/TestPyInterop.fs:167]: Do we want to / have to remove the test?

File: tests/Python/TestDependencyImport.fs [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+
+#if FABLE_COMPILER
+open System
+open Util.Testing
+open Thoth.Json.Core
+open Thoth.Json.Python
+open Fable.Core.PyInterop
+
+// /// https://github.com/fable-compiler/Fable/issues/4088#issuecomment-2751410558
```
Comment (dbrattli) [inline tests/Python/TestDependencyImport.fs:11]: This test works with #4100

**Comment by MangelMaxime** [comment]
Thanks to both of you, I will merge the PRs tomorrow
